// Mocks generated by Mockito 5.1.0 from annotations
// in provenance_dart/test/wallet_connect/wallet_connect_transform_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:provenance_dart/src/wallet_connect/encrypted_payload_helper.dart'
    as _i3;
import 'package:provenance_dart/src/wallet_connect/messages.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEncryptionPayload_0 extends _i1.Fake
    implements _i2.EncryptionPayload {}

/// A class which mocks [EncryptedPayloadHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptedPayloadHelper extends _i1.Mock
    implements _i3.EncryptedPayloadHelper {
  MockEncryptedPayloadHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EncryptionPayload encrypt(_i2.jsonEncodable? encodable) =>
      (super.noSuchMethod(Invocation.method(#encrypt, [encodable]),
          returnValue: _FakeEncryptionPayload_0()) as _i2.EncryptionPayload);
  @override
  String decryptAndVerify(_i2.EncryptionPayload? encryptionPayload) => (super
      .noSuchMethod(Invocation.method(#decryptAndVerify, [encryptionPayload]),
          returnValue: '') as String);
}
